### ISSUE TITLE
Send emails to test users after matching job descriptions with resume keywords.

### ISSUE THREAD

**Issue by ineelshah** [ineelshah/SRIJAS#12]

**Comment by jayrshah98** [comment]
Job description matched with the resume keywords and emails which include the link of the job description sent to the test users.
Thus, closing this issue.

**Comment by ineelshah** [comment]
Okay. I am adding a bug label to this. Please close when you have resolved this.

**Comment by ameyatathavadkar** [comment]
The issue has been resolved and SMTP is working fine now.
