### ISSUE TITLE
Add a punch line.

### ISSUE THREAD

**Issue by ineelshah** [ineelshah/SRIJAS#45]

**Comment by jayrshah98** [comment]
I suggest to use " Job Search has never been this easy " as a punch line

**Comment by ineelshah** [comment]
That is good. I guess since this is your suggestion, you can add this to the readme file and our portal.

**Comment by ineelshah** [comment]
And close the issue once you are done.

**Comment by jayrshah98** [comment]
Punchline added, so closing this issue
