### ISSUE TITLE
Setup infrastructure

### ISSUE THREAD

**Issue by ineelshah** [ineelshah/SRIJAS#5]
Setup all infrastructure that will be required through the project on AWS.

**Comment by ineelshah** [comment]
As discussed on our preferred channels on whatsapp and after having critical in person doscussions, I think we have a good enough infrastructure and all the related files look like they have been committed. I think we can close this issue now.

**Comment by ineelshah** [comment]
We discussed how we want to implement the project on Amazon ec2, and how most infrastructure related tasks and functionalities will be handled by @PvPatel-1001 . The discussion was fruitful and we decided on how we want to deploy our project.

**Comment by ineelshah** [comment]
The discussion can be found on Whatsapp group for SRIJAS.

**Comment by PvPatel-1001** [comment]
Created the infrastructure using terraform for web server, database server and scrapping server.
provided public access to the web server and provided private access to database server (can be accessed only through web server and the scrapping server).
Automated all the necessary installation on all the servers.
Automatically Fetched the project from github and placed the files accordingly to for running web server and the scrapping service.
Automatically configured the information of dynamically created database for both the servers.
running the post deployment testing and sending the reports to project email.
