### ISSUE TITLE
Add use cases to readme.

### ISSUE THREAD

**Issue by ineelshah** [ineelshah/SRIJAS#51]

**Comment by ineelshah** [comment]
@ameyatathavadkar can you do this?

**Comment by ameyatathavadkar** [comment]
Yeah sure.Please assign me to this issue

**Comment by ineelshah** [comment]
Great. Assigning you to this.

**Comment by ineelshah** [comment]
I suggest lets keep students as one of the use cases.

**Comment by ameyatathavadkar** [comment]
Agreed. We can also add working professionals as one of the use cases

**Comment by ineelshah** [comment]
True. We can keep the two as separate use cases since students can focus on study and rely on SRIJAS. Similarly, Working professionals can focus on their current works. These are very close but different use cases.

**Comment by ameyatathavadkar** [comment]
Use cases for both scenarios have been added.
